spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql

  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/user?serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
